{
 "title": "Gas",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "myfactor", "query": "0.01" },
   { "name": "cminkwh", "query": "10.616" },
   { "name": "priceperkwh", "query": "0.1338" },
   { "name": "gco2perkwh", "query": "202" },
   { "name": "calorificfactor", "query": "1.11" },
   { "name": "efficiency", "query": "0.9" },
   { "name": "conversionfactor", "query": "0.9336" },
   { "name": "calorificvalue", "query": "11.371" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": " sum(sum_over_time(delta(gmbd_counter_total{job=\"gas\"}[1m])[$__range:1m]) * $myfactor  ) ",
     "legendFormat": "Volume"
    },
    {
     "expr": " sum(sum_over_time(delta(gmbd_counter_total{job=\"gas\"}[1m])[$__range:1m]) * $myfactor * $cminkwh ) ",
     "legendFormat": "Calorific value"
    },
    {
     "expr": " sum(sum_over_time(delta(gmbd_counter_total{job=\"gas\"}[1m])[$__range:1m]) * ($myfactor * $cminkwh * $efficiency) / $calorificfactor ) ",
     "legendFormat": "Heating value"
    },
    {
     "expr": " sum(sum_over_time(delta(gmbd_counter_total{job=\"gas\"}[1m])[$__range:1m]) * $myfactor * $cminkwh * $priceperkwh) ",
     "legendFormat": "Costs"
    },
    {
     "expr": " sum(sum_over_time(delta(gmbd_counter_total{job=\"gas\"}[1m])[$__range:1m])  * $myfactor * $cminkwh * $gco2perkwh) ",
     "legendFormat": "CO2"
    }
   ]
  },
  {
   "title": "Heating Energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(delta(gmbd_counter_total{job=\"gas\"}[1m])[1h:1m] offset -1h)  * ($myfactor * $cminkwh * $efficiency) / $calorificfactor ) by (instance)",
     "legendFormat": "Heating value"
    },
    {
     "expr": "openweathermap_temperature_celsius  ",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Energy data per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(delta(gmbd_counter_total{job=\"gas\"}[1m])[24h:1m] offset -24h) *  ($myfactor * $cminkwh)  ) by (instance)",
     "legendFormat": "Calorific value"
    },
    {
     "expr": "sum(sum_over_time(delta(gmbd_counter_total{job=\"gas\"}[1m])[24h:1m] offset -24h) *  ($myfactor * $cminkwh * $efficiency) / $calorificfactor) by (instance)",
     "legendFormat": "Heating value"
    },
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Gas consumption per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(delta(gmbd_counter_total{job=\"gas\"}[1m])[24h:1m]  offset -24h) * $myfactor ) by (instance)",
     "legendFormat": "Gas volume"
    }
   ]
  },
  {
   "title": "Costs  per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(delta(gmbd_counter_total{job=\"gas\"}[1m])[24h:1m] offset -24h) * $myfactor * $cminkwh * $priceperkwh  ) by (instance)",
     "legendFormat": "Costs"
    }
   ]
  }
 ]
}